### ISSUE TITLE
Wipe data after user appointment (or when patient enters new code)?

### ISSUE THREAD

**Issue by cquinn5** [ssxsora/VMA-Mobile-App#4]
Up for further analysis, explore possibility for users to re-enter mobile code and get new appointment data

possible use case: patient comes back a week later for different procedure

**Comment by ssxsora** [comment]
Since @cquinn5 tested the delete secure storage data thing last week and we know it works, we can add an item to the menu that does that, then pushes the user back to the disclaimer page.

**Comment by cquinn5** [comment]
it worked? I don't remember

**Comment by ssxsora** [comment]
we can test again. it's the clearAllDataFromSecureStorage() function in helper-functions.ts

**Comment by mkcrto** [comment]
I'll test it out.

**Comment by mkcrto** [comment]
I created a new page that informs the user that they can clear all data by pressing the button on the page.  When they do so, secure storage is purged and the user is pushed back to the Enter Your Unique Code page.
